<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Imprimir</name>
   <tag></tag>
   <elementGuidId>51a7ffbc-9cbe-4770-97c9-f7c5029c921a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary px-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Imprimir
                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;row d-flexflex-nowrap wrapper mt-3&quot;]/div[@class=&quot;col-12 col-md-8 float-left py-3 bg-white float-left&quot;]/div[@class=&quot;form-inline float-right pl-md-3&quot;]/div[@class=&quot;form-group ml-2&quot;]/button[@class=&quot;btn btn-outline-primary px-3&quot;]</value>
   </webElementProperties>
</WebElementEntity>
