<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Abr</name>
   <tag></tag>
   <elementGuidId>c14bd353-dcdb-406c-8078-dc014706d960</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>monthcell tablesinglemonth</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sp-background-gray&quot;]/app-root[1]/app-asigna-ruta[1]/app-dialog[@class=&quot;ng-tns-c2-4&quot;]/div[@class=&quot;dialog animated fadeIn ng-tns-c2-4 ng-trigger ng-trigger-dialog&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 py-3 px-3 text-center&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-group&quot;]/my-date-picker[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mydp&quot;]/div[@class=&quot;selector selectorarrow selectorarrowleft&quot;]/table[@class=&quot;monthtable&quot;]/tbody[1]/tr[2]/td[@class=&quot;monthcell tablesinglemonth&quot;]</value>
   </webElementProperties>
</WebElementEntity>
