<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_28</name>
   <tag></tag>
   <elementGuidId>c3589dd7-c91e-4e81-a9e8-93710e5f8c37</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;row d-flex d-md-block flex-nowrap wrapper py-3&quot;]/div[@class=&quot;col-md-12 col-sm-12 float-left col py-3 pl-5 pr-3&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row d-flex d-md-block flex-nowrap wrapper px-3&quot;]/div[@class=&quot;col-6 pull-left pl-0&quot;]/div[@class=&quot;form-group&quot;]/my-date-picker[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;mydp&quot;]/div[@class=&quot;selector selectorarrow selectorarrowleft&quot;]/table[@class=&quot;caltable&quot;]/tbody[1]/tr[5]/td[@class=&quot;daycell currmonth tablesingleday&quot;]/div[@class=&quot;datevalue currmonth&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
